### ISSUE TITLE
Auto create new release when rules change

### ISSUE THREAD

**Issue by NateScarlet** [NateScarlet/gfwlist.acl#1]
As a notification enable by github `watch release only`

**Comment by NateScarlet** [comment]
@DearTanker
一个新版本提醒邮件应该是我能想到的最简洁方案了 
要自动pr不仅得去搞个专用bot帐号而且SSR发布用的acl我都找不到在哪

**Comment by DearTanker** [comment]
https://github.com/shadowsocks/shadowsocks-android/blob/master/core/src/main/assets/acl/gfwlist.acl

上面这个就是 Shadowsocks Android 版本的 gfwlist.acl 文件存储的路径，这个项目贡献代码的人不多，2位主力开发没有把精力放在这个文件上，导致在上个版本已经是2018年3月的。近期才有一个人帮忙更新了一下。如果阁下能够帮忙及时更新，并且做成自动化，那将是令人开心的一件事。

**Comment by NateScarlet** [comment]
上游不该涉及下游逻辑 我可能会去那项目里看看怎么自动化一下
